Repository jon011235/MARVIN, pull requests merged in 2023-10, with the labels that each got.

#1 Create .gitignore
  .gitignore
Labels: enhancement

#2 GitHub actions, devcontainer and dependabot
  .devcontainer/devcontainer.json
  .github/actions/verilog-compiler.vhdl
  .github/actions/verilog-linter.yml
  .github/dependabot.yml
Labels: enhancement

#3 Vs code extensions + readme
  .devcontainer/devcontainer.json
  README.md
Labels: enhancement

#4 Remove .v add .sv from .gitignore
  .gitignore
Labels: enhancement

#6 Update .gitignore remove old inclusions and improve readability
  .gitignore
Labels: Doc, Enhancement

#9 Rename verilog-compiler.vhdl to verilog-compiler.yml
  .github/actions/verilog-compiler.vhdl
  .github/actions/verilog-linter.yml
  .github/workflows/verilog-linter.yml
Labels: Easy Fix

#7 Graphics
  graphics/instructions.txt
  graphics/toplevel_debug.sv
  graphics/vga.sv
Labels: Enhancement

#11 Repair .gitignore remove indentations use empty lines instead
  .gitignore
Labels: Bug

#12 Repair gitignore remove comment in include statement
  .gitignore
Labels: Bug, Doc

#13 Create and set up Quartus project
  .gitignore
  quartus/MARVIN.qpf
  quartus/marvin.qsf
  quartus/marvin.sdc
  src/marvin.sv
  src/pkg.sv
Labels: Enhancement

#16 Add utils
  quartus/marvin.qsf
  src/marvin.sv
  src/utils/ckegen.sv
  src/utils/clksplit.sv
  src/utils/counter.sv
  src/utils/pwmgen.sv
Labels: Enhancement

#15 Update pin assignments for lowactive toplevel ports
  quartus/marvin.qsf
Labels: Easy Fix

#17 Update Quartus project files
  quartus/marvin.qsf
Labels: Easy Fix
